### ISSUE TITLE
Ran setup.sh, PC boots to blank screen

### ISSUE THREAD

**Issue by TwitchPid** [ilayna/Single-GPU-passthrough-amd-nvidia#22]
Running KDE Neon (Ubuntu 20.04 based) and I ran the setup.sh, now it just wont boot to anything... I think some of the configs in there are broken for my distronand it messed it up completely. Need some help recovering it.

AMD CPU, nVidia GPU of course, didn't do anything past step 2

**Comment by ilayna** [comment]
Run uninstall.sh from tty and try again

**Comment by TwitchPid** [comment]
> Run uninstall.sh from tty and try again
I can't boot into my pc

**Comment by TwitchPid** [comment]
OK I can boot again, don't really know if it was this or something else I did but I just had to rollback the kernel
